# Generated by Django 4.0.4 on 2022-04-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(default='group_avatar.png', upload_to='group_avatar/')),
                ('background', models.ImageField(default='group_background.png', upload_to='group_background/')),
                ('about', models.TextField(blank=True, max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('admin_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='profiles.profile')),
                ('followers', models.ManyToManyField(blank=True, related_name='follower_groups', to='profiles.profile')),
                ('staff', models.ManyToManyField(blank=True, related_name='staff_groups', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='GroupBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_type', models.CharField(choices=[('ban_group', 'Ban Group'), ('comment_ban', 'Comment ban')], max_length=15)),
                ('follower', models.ManyToManyField(blank=True, related_name='group_ban', to='profiles.profile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='group.group')),
            ],
        ),
    ]
